
project_id = "olcnfmrixglengxpiexf"

[functions.generate-workout]
verify_jwt = true

[functions.generate-workout-music]
verify_jwt = true

[functions.voice-chat]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

