// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olcnfmrixglengxpiexf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sY25mbXJpeGdsZW5neHBpZXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MjE2MTMsImV4cCI6MjA1NTA5NzYxM30.s7xLCt5VR5vZLzgWBM9oVab-K2Wiw1skDWfSt-hLq40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);